# Generated by Django 2.0 on 2019-06-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feiyong',
            name='feiyong_leixing',
        ),
        migrations.RemoveField(
            model_name='feiyong',
            name='feiyong_yhid',
        ),
        migrations.RemoveField(
            model_name='weihu',
            name='yonghu_id',
        ),
        migrations.RemoveField(
            model_name='weihu',
            name='yuangong_id',
        ),
        migrations.RemoveField(
            model_name='weixiudan',
            name='yonghu_id',
        ),
        migrations.RemoveField(
            model_name='yongliang',
            name='yonghu_id',
        ),
        migrations.DeleteModel(
            name='feiyong',
        ),
        migrations.DeleteModel(
            name='jiage',
        ),
        migrations.DeleteModel(
            name='weihu',
        ),
        migrations.DeleteModel(
            name='weixiudan',
        ),
        migrations.DeleteModel(
            name='yongliang',
        ),
        migrations.DeleteModel(
            name='yuangong',
        ),
    ]
