# Generated by Django 2.0 on 2019-06-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_auto_20190623_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feiyong',
            name='feiyong_leixing',
        ),
        migrations.RemoveField(
            model_name='feiyong',
            name='feiyong_yhid',
        ),
        migrations.DeleteModel(
            name='feiyong',
        ),
    ]
