# Generated by Django 2.0 on 2019-06-23 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0004_auto_20190623_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='feiyong',
            fields=[
                ('yonghu_id', models.IntegerField()),
                ('feiyong_danhaoid', models.IntegerField(primary_key=True, serialize=False)),
                ('feiyong_kaishi', models.DateField()),
                ('feiyong_jieshu', models.DateField()),
                ('feiyong_qian', models.CharField(max_length=20)),
                ('feiyong_zhuangtai', models.BooleanField()),
                ('feiyong_leixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.jiage')),
            ],
        ),
    ]
