# Generated by Django 2.0 on 2019-06-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_feiyong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feiyong',
            name='feiyong_leixing',
        ),
        migrations.DeleteModel(
            name='feiyong',
        ),
    ]
