# Generated by Django 2.0 on 2019-06-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_feiyong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feiyong',
        ),
        migrations.DeleteModel(
            name='jiage',
        ),
        migrations.RemoveField(
            model_name='weihu',
            name='yonghu_id',
        ),
        migrations.RemoveField(
            model_name='weihu',
            name='yuangong_id',
        ),
        migrations.RemoveField(
            model_name='weixiudan',
            name='yonghu_id',
        ),
        migrations.DeleteModel(
            name='xinwen',
        ),
        migrations.RemoveField(
            model_name='yongliang',
            name='yonghu_id',
        ),
        migrations.DeleteModel(
            name='weihu',
        ),
        migrations.DeleteModel(
            name='weixiudan',
        ),
        migrations.DeleteModel(
            name='yonghu',
        ),
        migrations.DeleteModel(
            name='yongliang',
        ),
        migrations.DeleteModel(
            name='yuangong',
        ),
    ]
