# Generated by Django 2.0 on 2019-06-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_auto_20190625_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weihu',
            name='weixiudan_id',
        ),
        migrations.RemoveField(
            model_name='weihu',
            name='yuangong_id',
        ),
        migrations.DeleteModel(
            name='weihu',
        ),
    ]
