# Generated by Django 2.0 on 2019-06-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_auto_20190625_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='weihu',
            fields=[
                ('weihu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('yonghu_id', models.IntegerField()),
                ('time', models.DateField()),
                ('money', models.CharField(max_length=20, null=True)),
                ('zhuangtai', models.BooleanField()),
                ('news', models.CharField(max_length=100)),
                ('stl', models.BooleanField()),
                ('weixiudan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.weixiudan')),
                ('yuangong_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.yuangong')),
            ],
        ),
    ]
