# Generated by Django 2.0 on 2019-06-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_weihu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feiyong',
        ),
    ]
