# Generated by Django 2.0 on 2019-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_delete_feiyong'),
    ]

    operations = [
        migrations.CreateModel(
            name='feiyong',
            fields=[
                ('yonghu_id', models.IntegerField()),
                ('feiyong_danhaoid', models.IntegerField(primary_key=True, serialize=False)),
                ('feiyong_kaishi', models.DateField()),
                ('feiyong_jieshu', models.DateField()),
                ('feiyong_leixing', models.IntegerField()),
                ('feiyong_qian', models.CharField(max_length=20)),
                ('feiyong_zhuangtai', models.BooleanField()),
                ('feiyong_company', models.CharField(max_length=20)),
            ],
        ),
    ]
